### ISSUE TITLE
Color extension method `trans` has been renamed to `translucent`

### ISSUE THREAD

**Issue by kasperosterbye** [ObjectProfile/Roassal3Documentation#4]
I did this in Pharo10, and Roassal loaded from library menu.

**Comment by NSUSpray** [comment]
I’ll also add: in the place where the force based layout is applied, the old comment “All the characters are displayed using a grid layout” remains, it should be replaced with “All the characters are displayed as a force-directed graph”.

**Comment by akevalion** [comment]
I have changed this
